In [3]:
import numpy as np

In [4]:
lst=[1,2,3,4,5]

In [5]:
arr=np.array(lst)

In [6]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

In [11]:
## MultiDimensional Array
lst1 = [1,2,3,4,5]
lst2 = [2,4,6,8,10]
lst3 = [3,6,9,11,13]

arr = np.array([lst1, lst2, lst3])

In [12]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 11, 13]])

In [13]:
arr.shape

(3, 5)

In [14]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  6,  8],
       [10,  3,  6],
       [ 9, 11, 13]])

In [15]:
arr.shape

(3, 5)

In [16]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 11, 13]])

In [18]:
arr[2][1]

np.int64(6)

In [21]:
arr[0:2,0:2]

array([[1, 2],
       [2, 4]])

In [20]:
arr[1:,3:]

array([[ 8, 10],
       [11, 13]])

In [25]:
arr=np.arange(0,10, step=2)

In [26]:
arr

array([0, 2, 4, 6, 8])

In [27]:
arr1=arr

In [28]:
arr1

array([0, 2, 4, 6, 8])

In [29]:
arr1[1:]=100

In [30]:
arr

array([  0, 100, 100, 100, 100])

In [31]:
arr1

array([  0, 100, 100, 100, 100])

In [32]:
arr1=arr.copy()

In [33]:
print(arr)
arr1[1:]=500
arr1

[  0 100 100 100 100]


array([  0, 500, 500, 500, 500])

In [7]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
arr = np.arange(0,10)

In [11]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5:]=10

In [13]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [14]:
val = 2

In [18]:
arr // 2

array([0, 0, 1, 1, 2, 5, 5, 5, 5, 5])

In [20]:
arr[arr<2]

array([0, 1])

In [21]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
arr1 = np.arange(1,10).reshape(3,3)

In [25]:
arr2 = arr1.copy()

In [26]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [29]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
np.random.rand(3,3)

array([[0.75602228, 0.7517757 , 0.18078621],
       [0.44315881, 0.01278187, 0.59215622],
       [0.53041365, 0.47867113, 0.16452285]])

In [31]:
arr_ex = np.random.randn(4,4)

In [32]:
arr_ex

array([[-2.38665917, -0.68447175, -0.95458554, -0.11641797],
       [ 0.58408193,  0.83976757, -0.98872103,  0.312961  ],
       [ 0.16961273, -1.1911103 ,  1.07152565, -0.66799334],
       [ 1.072756  ,  0.09205014,  0.51255832,  0.17071891]])